server:
  port: 8080
kafka:
  template:
    default-topic: gamestore
  producer:
    bootstrap-servers: localhost:29092,localhost:29093,localhost:29094
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
    properties:
      acks: all
      retries: 10
      retry.backoff.ms: 1000
  admin:
    properties:
      bootstrap.servers: localhost:29092,localhost:29093,localhost:29094