spring:
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: nonprod
  kafka:
    template:
      default-topic: gamestore
    producer:
      bootstrap-servers: localhost:29095,localhost:29096,localhost:29097
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
        retry.backoff.ms: 1000

---
spring:
  config:
    activate:
      on-profile: prod
  kafka:
    producer:
      bootstrap-servers: prod:9092,prod:9093,prod:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
logging:
  level:
    root: info